export const GET_ALL_COMENTS = 'GET_ALL_COMENTS'
export const GET_ALL_COMENTS_SUCCESS = 'GET_ALL_COMENTS_SUCCESS'

export const GET_COMENT_BY_ID = 'GET_COMENT_BY_ID'
export const GET_COMENT_BY_ID_SUCCESS = 'GET_COMENT_BY_ID_SUCCESS'

export const GET_COMENTS_BY_ID = 'GET_COMENT_BY_ID'
export const GET_COMENTS_BY_ID_SUCCESS = 'GET_COMENT_BY_ID_SUCCESS'

export const EDIT_COMENT_BY_ID = 'EDIT_COMENT_BY_ID'
export const EDIT_COMENT_BY_ID_SUCCESS = 'EDIT_COMENT_BY_ID_SUCCESS'

export const ADICIONA_COMENT = 'ADICIONA_COMENT'
export const ADICIONA_COMENT_SUCCESS = 'ADICIONA_COMENT_SUCCESS'

export const REMOVE_COMENT = 'REMOVE_COMENT'
export const SET_COMENTS = 'SET_COMENTS'