export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS'

export const GET_COMMENT_BY_ID = 'GET_COMMENT_BY_ID'
export const GET_COMMENT_BY_ID_SUCCESS = 'GET_COMMENT_BY_ID_SUCCESS'

export const GET_COMMENTS_BY_ID = 'GET_COMMENTS_BY_ID'
export const GET_COMMENTS_BY_ID_SUCCESS = 'GET_COMMENTS_BY_ID_SUCCESS'

export const EDIT_COMMENT_BY_ID = 'EDIT_COMMENT_BY_ID'
export const EDIT_COMMENT_BY_ID_SUCCESS = 'EDIT_COMMENT_BY_ID_SUCCESS'

export const ADICIONA_COMMENT = 'ADICIONA_COMMENT'
export const ADICIONA_COMMENT_SUCCESS = 'ADICIONA_COMMENT_SUCCESS'

export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const SET_COMMENTS = 'SET_COMMENTS'

export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const UPVOTE_COMMENT_SUCCESS = 'UPVOTE_COMMENT_SUCCESS';
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';
export const DOWNVOTE_COMMENT_SUCCESS = 'DOWNVOTE_COMMENT_SUCCESS';