export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS'

export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS'

export const EDIT_POST_BY_ID = 'EDIT_POST_BY_ID'
export const EDIT_POST_BY_ID_SUCCESS = 'EDIT_POST_BY_ID_SUCCESS'

export const CATEGORIES_FETCH_ALL = 'CATEGORIES::FETCH_ALL'
export const CATEGORIES_SET_ALL = 'CATEGORIES::SET_ALL'

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const SET_CATEGORIES= 'SET_CATEGORIES'

export const ADICIONA_POST = 'ADICIONA_POST'
export const ADICIONA_POST_SUCCESS = 'ADICIONA_POST_SUCCESS'

export const REMOVE_POST = 'REMOVE_POST'

export const UPVOTE_POST = 'UPVOTE_POST';
export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS';
export const DOWNVOTE_POST = 'DOWNVOTE_POST';
export const DOWNVOTE_POST_SUCCESS = 'DOWNVOTE_POST_SUCCESS';